[build]
  command = "npm run build"
  publish = "dist/prelim-project-supergpu/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
   NODE_VERSION = "20.19.0"
   
